### ISSUE TITLE
Goober support ?

### ISSUE THREAD

**Issue by vincent-vade** [gregberge/xstyled#188]
## 💬 Questions and Help

Hi,

First thank you for this great lib ! 

I've one question 
Do you have a plan for supporting [Goober](https://github.com/cristianbote/goober) out of the box ? 

Best regards

Vincent

**Comment by gregberge** [comment]
Hi @vincent-vade, no it is not in the pipe to support Goober. But xstyled has a very modular architecture. The package @xstyled/system, @xstyled/core and @xstyled/util should contain everything to create a @xstyled/goober.

It will not happen in this repo, because I don't want to maintain it but feel free to create it, publish it and maintain it. I will be happy to reference it in the docs.

**Comment by probablyup** [comment]
I'd be open to working on this @gregberge down the line if you'd be willing to keep it in the repo
