### ISSUE TITLE
Why not `reduceBreakpoints`  exported?

### ISSUE THREAD

**Issue by EmilioAiolfi** [gregberge/xstyled#195]
## 💬 Questions and Help

In version 1.x.x `reduceBreakpoints` is exported, and we were able to use it. Checking v2.x.x for a possible migration from 1.x.x to 2.x.x, the function is not exported. Is there a reason for that? This function that I use to create custom props with breakpoints in v1.x.x.
Is there another way to do it in 2.x.x?

Thanks

**Comment by gregberge** [comment]
In v2 I reduced the API surface for easily maintenance, `reduceBreakpoints` is an internal and was not documented in v1, that's why it was not a breaking change. Feel free to copy the source code of the function: https://github.com/gregberge/xstyled/blob/119410079910f0f2e3d1c88290344a2a61875362/packages/system/src/style.ts#L163-L182

**Comment by ivoilic** [comment]
@gregberge Would you be willing to export `reduceBreakpoints` from `@xstyled/system`? This and a few other utilities would be nice to have and are hard to copy since they rely on a bunch of other internal functions. This is what I was looking for in my own issue: #201

**Comment by gregberge** [comment]
@ivoilic no I am sorry, reducing the surface of the API give me ability to refactor code without breaking change.
