### ISSUE TITLE
Need Discord Server

### ISSUE THREAD

**Issue by jsartisan** [gregberge/xstyled#352]
Can we have a discord server to communicate bugs/issues/feature requests easily? Github issues are great but they are not real time. So it would be great to have a discord server that can help you build a community around this great product!

**Comment by D1no** [comment]
I like the idea but not much a fan of discord since it has limited discoverability leading to questions beeing asked over and over again. 

@gregberge can't you simply enable the new [github Discussions feature ](https://docs.github.com/en/discussions) on this repo?

I for would love to be able to ask questions on implementation ideas, since opening issues would be rude.

For example am dabbling around how to make mobile sites more accessible to people that for example have already set their  iPhones font size larger. You can do so:
```css
html {
    font: -apple-system-body
}
```
But than there is also the "increase text" option within safari throwing off the rem based 12col grid.
![Kapture 2022-02-18 at 22 27 52](https://user-images.githubusercontent.com/2397125/154763858-f3017932-3a64-40d6-af95-0d28a5b2a6fb.gif)

Anyway: I love this library and use it for my personal stuff. ❤️  from Berlin

**Comment by gregberge** [comment]
https://github.com/gregberge/xstyled/discussions/363 🎉
